### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by BrianWilliams-Coplex** [signifyd/magento2#1]
Hello,

Can you provide some instructions for installation? The standard installation process did not work correctly.

`$ composer require signifyd/connect` installed to the wrong location -- so I cloned and copied the files manually

once that was done bin/magento module:install Signifyd_Connect resulted in Unknown module(s): 'Signifyd_Connect'

Any hints/tips/help would be appreciated

Thanks!

**Comment by rbpotter** [comment]
When you say it installs to the wrong location, where is it being installed? It should be located under the vendor/signifyd folder (note: as of the RTM release of Magento 2 the module install directory changed to vendor and all modules are now prefixed by "module-").

**Comment by BrianWilliams-Coplex** [comment]
Ah, I apologize, I've tried many different ways to get this to install.

if I do `composer require signifyd/connect` it gives me this error: 
[InvalidArgumentException]                                                                                                                  
  Could not find package signifyd/connect at any version for your minimum-stability (alpha). Check the package spelling or your minimum-stability

If I clone the repo and copy manually to vendor/signifyd/connect Magento is unable to find the module when I run `magento module:enable Signifyd_Connect` 

Sorry for the confusion.

**Comment by rbpotter** [comment]
Here are the steps (all done in the M2 root directory):

1. composer config repositories.signifydmage2 git https://github.com/Signifyd/magento2.git 
2. composer require signifyd/module-connect:dev-master
3. php bin/magento module:enable Signifyd_Connect --clear-static-content 
4. php bin/magento setup:upgrade

**Comment by BrianWilliams-Coplex** [comment]
Sir, you are a gentleman and a Scholar. Thank you for your time and patience with helping me with this issue. Module installed and working.

**Comment by rbpotter** [comment]
Excellent, good to hear.
