### ISSUE TITLE
cannot place order after signify installation

### ISSUE THREAD

**Issue by balwant20** [signifyd/magento2#11]
i am using your signifyd module v2.0.8 with magento 2.1.7 and when i am placing order then i get an error like(Fatal error: Class 'Signifyd\Core\SignifydAPI' not found in /home/magento22/demo01/public_html/app/code/Signifyd/Connect/Helper/SignifydAPIMagento.php on line 11) before order completion.

**Comment by chrismorris528** [comment]
@balwant20 we'd be happy to help. Can you please email us at support@signifyd.com? We will be able to help you much faster through our support team.

**Comment by chrismorris528** [comment]
I'd suggest installing via composer and pulling down our latest version which is 2.1.1
