### ISSUE TITLE
Error after upgrade (what version of signifyd-php?)

### ISSUE THREAD

**Issue by James-Moon-Audio** [signifyd/magento2#13]
Upgraded today and am now getting the following error when cancelling an order:

[03-Jan-2018 19:46:41 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Signifyd\Connect\Helper\SignifydAPIMagento::cancelGuarantee() in /app/mqbydmn4mmpdk/vendor/signifyd/module-connect/Helper/PurchaseHelper.php:396
Stack trace:
#0 /app/mqbydmn4mmpdk/vendor/signifyd/module-connect/Observer/Cancel.php(64): Signifyd\Connect\Helper\PurchaseHelper->cancelCaseOnSignifyd(Object(Magento\Sales\Model\Order))
#1 /app/mqbydmn4mmpdk/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Signifyd\Connect\Observer\Cancel->execute(Object(Magento\Framework\Event\Observer))
#2 /app/mqbydmn4mmpdk/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Signifyd\Connect\Observer\Cancel), Object(Magento\Framework\Event\Observer))
#3 /app/mqbydmn4mmpdk/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#4 /app/mqbydmn4mmpdk/init/var/generation/Magento/Staging/ in /app/mqbydmn4mmpdk/vendor/signifyd/module-connect/Helper/PurchaseHelper.php on line 396

Relevant composer data - {
            "name": "signifyd/module-connect",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/Signifyd/magento2.git",
                "reference": "4e378153b35475d00e38ba5b05c6e5488894c651"
            },
            "require": {
                "signifyd/signifyd-php": "0.1.*"
            },
            "type": "magento2-module",
            "autoload": {
                "files": [
                    "registration.php"
                ],
                "psr-4": {
                    "Signifyd\\Connect\\": ""
                }
            },
            "description": "Signifyd integration for Magento",
            "time": "2017-12-28T00:27:56+00:00"
        },
        {
            "name": "signifyd/signifyd-php",
            "version": "v0.1.7",
            "source": {
                "type": "git",
                "url": "https://github.com/signifyd/signifyd-php.git",
                "reference": "6a457bc9f14a9024a17bdef788b0944344c3f915"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/signifyd/signifyd-php/zipball/6a457bc9f14a9024a17bdef788b0944344c3f915",
                "reference": "6a457bc9f14a9024a17bdef788b0944344c3f915",
                "shasum": ""
            },
            "require": {
                "php": ">=5.4.0"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Signifyd\\": "lib/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "description": "Signifyd client API plugin for PHP",
            "time": "2017-05-24T15:48:34+00:00"
        },

Had updated via composer and launched.  Do I need to manually update signifyd-php?

**Comment by James-Moon-Audio** [comment]
When I try to update "composer update signifyd/signifyd-php" I get "Nothing to install or update"

**Comment by chrismorris528** [comment]
@James-Moon-Audio we'd be happy to help. Can you send us an email at support@signifyd.com so that someone from our support team can help resolve your issue?

**Comment by James-Moon-Audio** [comment]
I reached out to support.

I'm not an expert, but it looks like composer.json - https://github.com/signifyd/magento2/blob/master/composer.json is referencing "signifyd/signifyd-php":"0.1.*"  even though it is expecting version 1.1.2 with the new cancel guarantee changes.

I believe this is why composer is not properly updating the dependency and causing errors.

Should composer.json be updated to reflect the new requirement?
