### ISSUE TITLE
Compatibility with Magento version and submodules not declared and not publicized

### ISSUE THREAD

**Issue by linden2015** [signifyd/magento2#14]
Preconditions:
* Any version of `signifyd/module-connect`

Expected:
* Dependencies on Magento 2 submodule packages and version constraints specified in `composer.json` 
* Compatibility with Magento 2 version described in release notes

Actual:
* No dependencies declared on Magento 2 submodule packages in `composer.json`, even though they are depended upon in the code
* No compatibility with Magento 2 described in release notes

See:
* [Magento DevDocs: Module version dependencies](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/versioning/dependencies.html)

**Comment by chrismorris528** [comment]
@linden2015 thanks for the feedback. We are working to fix this issue. It's currently slated for our next release.

**Comment by chrismorris528** [comment]
this has been resolved in the latest extension version v2.2.1
