### ISSUE TITLE
Error during upgrade to Magento 2.2.2

### ISSUE THREAD

**Issue by linden2015** [signifyd/magento2#15]
Preconditions:

* A Magento 2.1.10 installation
* signifyd/module-connect 2.1.1 installed through composer and this Github repo specified under repositories (type: vcs)

Steps:

* Upgrade to Magento 2.2.2
* Run `php bin/magento module:enable --all`
* Run `php bin/magento setup:upgrade`

Actual:

* Error: `Module 'Magento_SalesRule': Upgrading data.. Invalid Document Element 'route': Duplicate key-sequence ['signifyd'] in unique identity-constraint 'uniqueRouteFrontName'. Line: 5`

Expected:

* No error

Notes:

* I noticed someone who upgraded from Magento 2.2.1 to 2.2.2 had the same error: https://magento.stackexchange.com/q/204166/56637

**Comment by chrismorris528** [comment]
@linden2015 the conflict is caused because the Signifyd module built-in into Magento 2.2 and our extension use the same route. You'll need to disable the native Magento module before installing the extension. We are exploring ways to avoid the conflict during the installation process.

**Comment by chrismorris528** [comment]
This has been resolved in the latest version of the extension v2.2.1
