### ISSUE TITLE
Installation v2.2.5

### ISSUE THREAD

**Issue by SamB-GB** [signifyd/magento2#17]
I am trying to install this on v2.2.5 but getting the following error when recompiling.

Interception cache generation... 6/7 [========================>---]  85% 55 secs 522.0 MiBErrors during compilation:
	Signifyd\Connect\Observer\Purchase\AuthorizenetDirectpost
		Missed required argument objectManagerInterface in parent::__construct call. File: /srv/public_html/vendor/signifyd/module-connect/Observer/Purchase/AuthorizenetDirectpost.php
Total Errors Count: 1

                                           
  [Magento\Framework\Validator\Exception]  
  Error during compilation

**Comment by chrismorris528** [comment]
This has been fixed in 3.0.1
