### ISSUE TITLE
Invalid method Signifyd\Connect\Model\Casedata::updateOrder 

### ISSUE THREAD

**Issue by sunilit42** [signifyd/magento2#19]
Hello,

https://github.com/signifyd/magento2/blob/master/Helper/Retry.php#L93

you are trying to call the protected method, so it showing error when cron try to update order status

can you please help us on that?

**Comment by chrismorris528** [comment]
@sunilit42 we are working on a fix for this.

**Comment by chrismorris528** [comment]
this was fixed in 3.0.2. Thanks for reporting the issue.
