### ISSUE TITLE
Error "There is one or more database modifications missing" is shown incorrectly

### ISSUE THREAD

**Issue by bradberger** [signifyd/magento2#20]
In 3.0.1 when saving config, the "There is one or more database modifications missing." error message is shown incorrectly. This is because the code doesn't take into account the possibilities of database prefixes.

The solution is to add this before line 77 of [Observer/Config.php](https://github.com/signifyd/magento2/blob/master/Observer/Config.php#L77):

```php
$table = $this->resource->getTableName($table);
```
That will add the database table prefix if available.

**Comment by chrismorris528** [comment]
fixed in 3.0.2. Thanks for reporting the issue.
