### ISSUE TITLE
Store configuration issue when case updates throw cron

### ISSUE THREAD

**Issue by pratikrgandhi** [signifyd/magento2#22]
Hi,

Issue found when we configure different API key on multiple stores
-> Case submit successfully and Case status on REVIEW
-> When Case updates through CRON, that time it takes global configuration value.

Issue from here it's not getting store Id from entity when entity is CaseData
https://github.com/signifyd/magento2/blob/master/Helper/ConfigHelper.php#L110

We have tried below code after this change, it's working fine with multiple stores.
[SIGNIFYD_CONNECT_STORE_BUG.TXT](https://github.com/signifyd/magento2/files/2624981/SIGNIFYD_CONNECT_STORE_BUG.TXT)

**Comment by sig-chrismorris528** [comment]
@partha-mukherjee this was fixed in 3.1
