### ISSUE TITLE
Multi-store cron processing

### ISSUE THREAD

**Issue by frustratedtech** [signifyd/magento2#24]
There seems to be an issue where the magento 2.2 cron runs and pushes cases for orders on different stores even though they are set to NO for enabling the module.

Our setup has 7 stores and only 2 stores have Signifyd enabled.
If we disable the cron, we do not see the orders for the disabled stores in the signifyd console.  This is the expected behavior.
If we enable the cron, we see the orders for the disabled stores in the signifyd console.  This should not be happening.

We are on Magento 2.2.6 with the v1.1.1 Signifyd extension.

**Comment by sig-chrismorris528** [comment]
@frustratedtech 1.1.1 is almost 3 years old. Have you tried updating to the latest versino 3.1? We have made a lot of changes to the cron since then.

**Comment by frustratedtech** [comment]
@sig-chrismorris528 its 3.1.1 sorry.

**Comment by sig-chrismorris528** [comment]
@frustratedtech can you open a ticket using the link below so we can investigate further? This will ensure you get the fastest response. https://community.signifyd.com/support/s/contactsupport

When you open the ticket please provide the signifyd_connect.log and debug.log. Also please provide a few example orders that were not suppose to be go to Signifyd.
