### ISSUE TITLE
Dependency (signifyd/signifyd-php)

### ISSUE THREAD

**Issue by mantonuk** [signifyd/magento2#4]
hi there.
signifyd/signifyd-php has **released 1.0.1** version.
maybe have sence to update dependency in composer.json
tnx

**Comment by chrismorris528** [comment]
@ebanolopes can you take a look?

**Comment by ebanolopes** [comment]
I'll take a look and give a feedback soon as possible.

**Comment by chrismorris528** [comment]
@mantonuk sorry for the slow response. Is this still an issue for you? If so would you mind emailing us at support@signifyd.com? Our team can help you much faster there.
