### ISSUE TITLE
Fatal error: Class 'Signifyd\Core\SignifydAPI' not found in app/code/Signifyd/Connect/Helper/SignifydAPIMagento.php on line 12

### ISSUE THREAD

**Issue by sundeep570** [signifyd/magento2#6]
As i installed Signifyd extension getting this error
Fatal error: Class 'Signifyd\Core\SignifydAPI' not found in app/code/Signifyd/Connect/Helper/SignifydAPIMagento.php on line 12
so what is the solution for this..and also same error in while compiling the code.
please assist me.
Thanks in advance.

**Comment by ebanolopes** [comment]
Hi, @sundeep570, looks like you're missing the Singnifyd library. Did you've installed the extension using Magento Web Wizard? Please check if you have this file on your store: vendor/signifyd/signifyd-php/lib/Core/SignifydAPI.php

**Comment by sundeep570** [comment]
No, I didn't installed the extension using Magento Web Wizard? and also i didn't found this file in my vendor -->vendor/signifyd/signifyd-php/lib/Core/SignifydAPI.php .

**Comment by ebanolopes** [comment]
The solution is to install the extension using Web Wizard, here are the steps:

1. Purchase the extension on Magento Marketplace, it is free, so no costs, but it is needed to purchase anyway: https://marketplace.magento.com/signifyd-module-connect.html
2. Go to Magento admin panel and access System > Tools > Web Setup Wizard
3. If you've never used this wizard before, you have to setup your marketplace keys. That is done on "System Config" menu option, inside the Setup Wizard tool. You can find your keys at Magento Marketplace website, just access https://marketplace.magento.com/customer/accessKeys/ (make sure you're logged in)
4. Keys configured, go to Setup Wizard home and click on "Component Management"
5. Click on [Sync] button, bellow "Last Sync" to make sure Magento will find your purchase
6. Below "New Purchases" count there is a link "Install", click on it
7. Locate Signifyd extension and click on "Install" on action column
8. Follow the rest of the process and it should work fine

Hope it helps :) If you have any other questions or new problems appears, please, let me know. Also, if it works, inform us here, so we can close this issue.

**Comment by ebanolopes** [comment]
Hi, @sundeep570, you've been able to put the extension to work?

**Comment by sundeep570** [comment]
hi, @ebanolopes in my instance when I clicked Component Management in Setup Wizard home then it keeps on loading. I have tried but unable to do.
Sorry for late reply.

**Comment by ebanolopes** [comment]
Hi, the Component Management it is a default built in functionality of Magento. Can you please check you installation, if everything it is on place? I suggest that you take a look at the browser inspector to check for any JavaScript errors, that can be a start.

Another way to try to figure out what's wrong with the Component Management is to get a fresh install of Magento, separated from the one you already have and check if it works on the same environment.

If I can help in any other way to figure it out what's going on with your installations, please, let me know.

**Comment by sundeep570** [comment]
Hi, @ebanolopes I am checking and once it is done I will share with you, thanks for the quick response.

**Comment by ebanolopes** [comment]
Hi, @sundeep570, have you the chance to check and sold the issue? Let me know if there is anything else I can help.

**Comment by dan-ding** [comment]
use composer to install signifyd/signfiyd-php, and forget that marketplace stuff.

**Comment by ebanolopes** [comment]
Yeah, composer it is a good way also. But for Signifyd, marketplace works good too. You can choose whay you think it is the best for you.

**Comment by ebanolopes** [comment]
@sundeep570, I'm closing this issue since I'vent received any other responses. If you still have this issue on your installation and you need any help, please, let me know and I'be happy to assist you.
